### ISSUE TITLE
Settings highlight box margins

### ISSUE THREAD

**Issue by ewerybody** [lancewilhelm/horizon-extended#3]
Hello again! Just some tiny thing:

I love these highlight lines and boxes! But when **searching** in the **Settings**-tab and either an item or the whole settings list is highlighted there seems to be no gap on the right and could be less on the left:
![image](https://user-images.githubusercontent.com/218956/153578307-dbd8fac4-0d01-4df2-a778-4d2dd17b9631.png)

just mocked-up this would imho look a little nicer:
![image](https://user-images.githubusercontent.com/218956/153578874-a3b3d2e2-a97a-4be8-a5d0-0ba029507648.png)

**Comment by lancewilhelm** [comment]
That is a good find. I have not messed with the padding/margin yet on any of the items in the theme yet so it may take me a bit to find it but I will take a look. I like your proposed change, it is clean.

**Comment by lancewilhelm** [comment]
OK here is what I have found. The color theming that is performed by horizon extended can only touch the colors of the elements, it does not touch the styling of them. From what I found in the developer tools, what you would want to do is change the width and padding of the classes .monaco-list and .monaco-scrollable-element (there might be a couple others as well). Unfortunately this is not too easy but it is doable by creating a new stylesheet and then referencing that stylesheet in your settings.json file. I found a the following stackoverflow post talking about this process. 

https://stackoverflow.com/questions/40697223/how-to-change-error-styles-in-vs-code

I'm sorry, but it looks like it cannot be handled by the theme at this time.

**Comment by lancewilhelm** [comment]
This extension enables the solutions in the stackoverflow post above. 

https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

It also enables some themes like synthwave to have a glow effect on the text since it allows theme makers to make actual css changes. I will keep this ugly settings border in the back of mind though and may consider muting it in a future build just to maintain the clean appearance.

**Comment by ewerybody** [comment]
Ahhh alright! I see. Thanks for looking into it anyway! 🙇‍♀️

So Maybe we could forward this to the main VS Code devs?
I mean there is SO much and they have LOADs of superflous ideas in their tracker but I recently had something fixed in a couple of weeks. 
Their styles don't have such a popping hightlight box but seems there is literally room for improvement.

**Comment by lancewilhelm** [comment]
Yea not a bad idea! This is probably something they just haven't noticed but could be fixed easily in a matter of minutes on the master stylesheet.

**Comment by ewerybody** [comment]
OK.. I was already writing on a report and **actually** read the instructions. i.e. "look for duplicates.." found none but then though to look how it is on the Insiders build:
![image](https://user-images.githubusercontent.com/218956/153707503-ee72330f-6b1c-4e6c-ae13-547019bc67f9.png)
This is **Horizon Extended** on **1.65.0-insider**

Turns out: There is now an adjustable splitter inbetween the settings items and content. 🙂

**Comment by lancewilhelm** [comment]
That is awesome! I may have to pop over and check it out!
