### ISSUE TITLE
Display Errors on Filename in File Explorer

### ISSUE THREAD

**Issue by HikariS97** [lancewilhelm/horizon-extended#4]
os: Monterey 12.2.1
vscode ver:1.64.2

The error only appears when the light theme was selected.
<img width="655" alt="截屏2022-02-23 08 06 12" src="https://user-images.githubusercontent.com/48763518/155240808-758a76ed-83cc-4fe3-bbf9-8a4c0c7d5aac.png">

I'll be appreciated if any advice... I really love the theme.

**Comment by lancewilhelm** [comment]
Yea that is very bad! Let me look into it and see if I can get a quick fix pushed.

**Comment by lancewilhelm** [comment]
I believe that I have found the bad color choice. In my case, it is a carry over from the dark theme for files that are ignored in a git repo. This may pertain to other scenarios but that is where I am seeing the issue. I will change the theming to a gray that is visible.

**Comment by lancewilhelm** [comment]
![Screen Shot 2022-02-22 at 6 39 43 PM](https://user-images.githubusercontent.com/11323174/155253245-cea36db3-5640-4a68-b102-9619ef7e587e.png)
 
I believe I have a fix in place and published in 0.1.7. Check it out and let me know.

**Comment by HikariS97** [comment]
Thank you. It looks great!
