### ISSUE TITLE
Line maker in Scrollbar looks like error. Other color maybe?

### ISSUE THREAD

**Issue by ewerybody** [lancewilhelm/horizon-extended#5]
Hey there again! I'm still **very much enjoying** this theme!!!
But as it is with these things: The longer one uses them the more subtle annoyances arise!

For instance: I stopped using the minimap to have more space, less noise and I like that the actual scrollbar is transparent.

But now I keep looking for my line in the scrollbar! Thinking this red bar is some error line!:
![image](https://user-images.githubusercontent.com/218956/164497938-72f51e22-ab64-4d2e-b7ce-753609404e30.png)

I know this is like the signature color of this theme
but WOULD it be possible to have this changed? Or customizable?

**Comment by lancewilhelm** [comment]
@ewerybody, I apologize for my very very extended absence from this project. In the case that you or anyone else is using this theme, here is an answer!

You are right, this seemingly "red" bar is the main theme color manifesting itself there. More specifically, that color is driven by the cursor color. I personally like the pink cursor and I got used to the line, but there is a workaround if you would like to change them.

You can change the `editorCursor.foreground` property in your `workbench.colorCustomizations` in the settings. Here is an example. I changed my cursor color to gray to demonstrate.

![Screenshot 2024-06-28 at 8 46 15 PM](https://github.com/lancewilhelm/horizon-extended/assets/11323174/f6d4831e-7d67-42b3-b82e-acbfed606fd6)
![Screenshot 2024-06-28 at 8 46 30 PM](https://github.com/lancewilhelm/horizon-extended/assets/11323174/28cc746c-f05b-44ba-baf6-c455ad1732d3)

You can see that not only did that line change, but so did the cursor.

**Comment by ewerybody** [comment]
Really nice tip! Thank you!! 🙏
