### ISSUE TITLE
Word highlight, selection and search highlight are super similar

### ISSUE THREAD

**Issue by ewerybody** [lancewilhelm/horizon-extended#6]
Hello there! 👋
I know I should be in a cellar to code properly but well, sometimes I'm not and when its rather bright around I have a hard time making out my selection. Especially when I searched for a term.
Here for instance I searched for `instance`, clicked inside the second occurence and selected `nstan`:
> ![image](https://user-images.githubusercontent.com/218956/164499532-cc33ac77-b842-4093-90fa-d4d8b6326a08.png)

I have to squint a little and really take care to see what I'm selecting.

Its not so bad when I'm **not searching**:
> ![image](https://user-images.githubusercontent.com/218956/164499425-c67fd6c0-996e-47bf-88eb-318c7444af67.png)

but could still be improved I think.

I just checked back with the original themes: They aren't really way better! 🕵️‍♂️
> ![image](https://user-images.githubusercontent.com/218956/164502608-efa9a1c4-bf69-48ad-bd69-b90ee134d055.png)

**One Dark Pro** (the one I turned my back to) uses some lines there! Nice:
> ![image](https://user-images.githubusercontent.com/218956/164502303-53e01543-95c0-41c3-934c-afed98d0f264.png)

Sorry for the long post. What do you think?

**Comment by lancewilhelm** [comment]
This is a good point. I have struggled with this fact myself sometimes. I have some changes cooking that brighten up the selection a bit, but not too much I think. I will try and push this change here very soon.

**Comment by lancewilhelm** [comment]
Addressed in v0.2.0
