### ISSUE TITLE
YAML strings

### ISSUE THREAD

**Issue by p1x44r** [lancewilhelm/horizon-extended#7]
Hi,

This is an excellent and unique theme that made me switch from the one I've been using for probably over a year. Great job!

Just a quick question on YAML strings (unquoted). Are these meant to be white or some other color?

<img width="709" alt="Screen Shot 2022-09-04 at 7 04 14 PM" src="https://user-images.githubusercontent.com/1068500/188336936-577b58ff-be04-422c-9287-9b117096f306.png">

Thanks.

**Comment by lancewilhelm** [comment]
@p1x44r, thanks for submitting this issue. I apologize it took me so long to get back to you. In the case that you are using the theme still here is an answer.

Unquoted YAML strings were indeed always white. Quoted of course is the typical green.

That being said, the theme is due for an update, and some other popular and modern themes color their unquoted strings in the same fashion as their quoted strings. I will likely include this in an update!

**Comment by lancewilhelm** [comment]
Addressed in v0.2.0
