### ISSUE TITLE
This theme but without italics

### ISSUE THREAD

**Issue by ketozhang** [lancewilhelm/horizon-extended#8]
I like this theme, however vertical bar `|` looks like a slash.

**Comment by lancewilhelm** [comment]
@ketozhang, I apologize for the very late response. In the case that you or anyone else are interested, I will add a version that does not have italics.

**Comment by lancewilhelm** [comment]
Addressed in v0.2.0

**Comment by ketozhang** [comment]
Thank you! Love this theme.
